package mysql

var LoveDict = map[string]string{
	"cove_screening":       "Cove screening",
	"plasma":               "Plasma",
	"registry":             "registry",
	"key":                  "Key",
	"item_type":            "Item Type",
	"publication_year":     "Publication Year",
	"author":               "Author",
	"title":                "Title",
	"publication_title":    "Publication Title",
	"isbn":                 "ISBN",
	"issn":                 "ISSN",
	"doi":                  "DOI",
	"url":                  "Url",
	"abstract_note":        "Abstract Note",
	"date":                 "Date",
	"date_added":           "Date Added",
	"date_modified":        "Date Modified",
	"access_date":          "Access Date",
	"pages":                "Pages",
	"num_pages":            "Num Pages",
	"issue":                "Issue",
	"volume":               "Volume",
	"number_of_volumes":    "Number Of Volumes",
	"journal_abbreviation": "Journal Abbreviation",
	"short_title":          "Short Title",
	"series":               "Series",
	"series_number":        "Series Number",
	"series_text":          "Series Text",
	"series_title":         "Series Title",
	"publisher":            "Publisher",
	"place":                "Place",
	"language":             "Language",
	"rights":               "Rights",
	"type":                 "Type",
	"archive":              "Archive",
	"archive_location":     "Archive Location",
	"library_catalog":      "Library Catalog",
	"call_number":          "Call Number",
	"extra":                "Extra",
	"notes":                "Notes",
	"file_attachements":    "File Attachments",
	"link_attachments":     "Link Attachments",
	"manual_tags":          "Manual Tags",
	"automatic_tags":       "Automatic Tags",
	"editor":               "Editor",
	"series_editor":        "Series Editor",
	"translator":           "Translator",
	"contributor":          "Contributor",
	"attorney_agent":       "Attorney Agent",
	"book_author":          "Book Author",
	"cast_member":          "Cast Member",
	"commenter":            "Commenter",
	"composer":             "Composer",
	"counsel":              "Counsel",
	"interviewer":          "Interviewer",
	"producer":             "Producer",
	"recipient":            "Recipient",
	"reviewed_author":      "Reviewed Author",
	"scriptwriter":         "Scriptwriter",
	"words_by":             "Words By",
	"guest":                "Guest",
	"number":               "Number",
	"edition":              "Edition",
	"running_time":         "Running Time",
	"scale":                "Scale",
	"medium":               "Medium",
	"artwork_size":         "Artwork Size",
	"filing_date":          "Filing Date",
	"application_number":   "Application Number",
	"assignee":             "Assignee",
	"issuing_authority":    "Issuing Authority",
	"country":              "Country",
	"meeting_name":         "Meeting Name",
	"conference_name":      "Conference Name",
	"court":                "Court",
	"references":           "References",
	"reporter":             "Reporter",
	"legal_status":         "Legal Status",
	"priority_numbers":     "Priority Numbers",
	"programming_language": "Programming Language",
	"version":              "Version",
	"system":               "System",
	"code":                 "Code",
	"code_number":          "Code Number",
	"section":              "Section",
	"session":              "Session",
	"committee":            "Committee",
	"history":              "History",
	"legislative_body":     "Legislative Body",
}

var ictrpDict = map[string]string{
	"cove_screening":          "cove_screening",
	"cove_import_date":        "cove_import_date",
	"cove_update_date":        "cove_update_date",
	"trial_id":                "TrialID",
	"last_refreshed_on":       "Last Refreshed on",
	"public_title":            "Public title",
	"scientific_title":        "Scientific title",
	"acronym":                 "Acronym",
	"primary_sponsor":         "Primary sponsor",
	"date_registration":       "Date registration",
	"date_registration_3":     "Date registration3",
	"export_date":             "Export date",
	"source_register":         "Source Register",
	"web_address":             "web address",
	"recruitment_status":      "Recruitment Status",
	"other_records":           "other records",
	"inclusion_agemin":        "Inclusion agemin",
	"inclusion_agemax":        "Inclusion agemax",
	"inclusion_gender":        "Inclusion gender",
	"date_enrollement":        "Date enrollement",
	"target_size":             "Target size",
	"study_type":              "Study type",
	"study_design":            "Study design",
	"phase":                   "Phase",
	"countries":               "Countries",
	"contact_firstname":       "Contact Firstname",
	"contact_lastname":        "Contact Lastname",
	"contact_address":         "Contact Address",
	"contact_email":           "Contact Email",
	"contact_tel":             "Contact Tel",
	"contact_affiliation":     "Contact Affiliation",
	"inclusion_criteria":      "Inlcusion Criteria",
	"exclusion_criteria":      "Exclusion Criteria",
	"condition":               "Condition",
	"intervention":            "Intervention",
	"primary_outcome":         "Primary outcome",
	"results_date_posted":     "results date posted",
	"results_date_completed":  "results date completed",
	"results_url_link":        "results url link",
	"retrospective_flag":      "Retrospective flag",
	"bridging_flag_truefalse": "Bridging flag truefalse",
	"bridged_type":            "Bridged type",
	"results_yes_no":          "results yes no",
}

var coveDict = map[string]bool{
	"is_covid":                          true,
	"is_trial":                          true,
	"is_observational":                  true,
	"is_duplicate":                      true,
	"is_rct":                            true,
	"review_status":                     true,
	"reviewer_name":                     true,
	"source":                            true,
	"source_id":                         true,
	"entry_type":                        true,
	"entry_type_certainty":              true,
	"url":                               true,
	"url_certainty":                     true,
	"title":                             true,
	"title_certainty":                   true,
	"abstract":                          true,
	"abstract_certainty":                true,
	"authors":                           true,
	"authors_certainty":                 true,
	"corresp_author_lastname":           true,
	"corresp_author_lastname_certainty": true,
	"corresp_author_email":              true,
	"corresp_author_email_certainty":    true,
	"journal":                           true,
	"journal_certainty":                 true,
	"doi":                               true,
	"doi_certainty":                     true,
	"status":                            true,
	"status_certainty":                  true,
	"status_date":                       true,
	"status_date_certainty":             true,
	"registration_date":                 true,
	"registration_date_certainty":       true,
	"country":                           true,
	"country_certainty":                 true,
	"countries":                         true,
	"countries_certainty":               true,
	"continents":                        true,
	"continents_certainty":              true,
	"international":                     true,
	"international_certainty":           true,
	"covid_status":                      true,
	"covid_status_certainty":            true,
	"randomized":                        true,
	"randomized_certainty":              true,
	"blinding":                          true,
	"blinding_certainty":                true,
	"longitudinal_structure":            true,
	"longitudinal_structure_certainty":  true,
	"n_arms":                            true,
	"n_arms_certainty":                  true,
	"n_enrollment":                      true,
	"n_enrollment_certainty":            true,
	"population_condition":              true,
	"population_condition_certainty":    true,
	"population_gender":                 true,
	"population_gender_certainty":       true,
	"population_age":                    true,
	"population_age_certainty":          true,
	"intervention_type":                 true,
	"intervention_type_certainty":       true,
	"intervention_name":                 true,
	"intervention_name_certainty":       true,
	"intervention_substance":            true,
	"intervention_substance_certainty":  true,
	"control_type":                      true,
	"control_type_certainty":            true,
	"control":                           true,
	"control_certainty":                 true,
	"out_primary_measure":               true,
	"out_primary_desc":                  true,
	"out_primary_timeframe":             true,
	"out_primary_measure_certainty":     true,
	"out_primary_desc_certainty":        true,
	"out_primary_timeframe_certainty":   true,
	"start_date":                        true,
	"start_date_certainty":              true,
	"end_date":                          true,
	"end_date_certainty":                true,
	"results_available":                 true,
	"results_available_certainty":       true,
	"results_expected_date":             true,
	"results_expected_date_certainty":   true,
	"ipd_sharing":                       true,
	"ipd_sharing_certainty":             true,
	"linkage_info":                      true,
	"linkage_info_certainty":            true,
	"out_secondary_measure":             true,
	"out_secondary_desc":                true,
	"out_secondary_timeframe":           true,
	"out_secondary_measure_certainty":   true,
	"out_secondary_desc_certainty":      true,
	"out_secondary_timeframe_certainty": true,
	"inclusion_criteria":                true,
	"inclusion_criteria_certainty":      true,
	"exclusion_criteria":                true,
	"exclusion_criteria_certainty":      true,
	"funding":                           true,
	"funding_certainty":                 true,
	"funding_type":                      true,
	"funding_type_certainty":            true,
	"protocol_available":                true,
	"protocol_available_certainty":      true,
	"protocol_link":                     true,
	"protocol_link_certainty":           true,
	"extraction_comment":                true,
}

var ctDict = map[string]bool{
	"cove_screening":                 true,
	"cove_import_date_migration":     true,
	"cove_update_date_migration":     true,
	"nct_id":                         true,
	"date_study_first_submitted":     true,
	"date_study_first_posted":        true,
	"date_last_update_posted":        true,
	"date_started":                   true,
	"date_started_type":              true,
	"date_completed":                 true,
	"date_completed_type":            true,
	"status":                         true,
	"brief_title":                    true,
	"official_title":                 true,
	"brief_summary":                  true,
	"detailed_description":           true,
	"study_type":                     true,
	"phase":                          true,
	"allocation":                     true,
	"intervention_model":             true,
	"intervention_model_description": true,
	"primary_purpose":                true,
	"masking":                        true,
	"condition":                      true,
	"intervention_type":              true,
	"intervention_name":              true,
	"intervention_desc":              true,
	"eligibility_criteria":           true,
	"gender":                         true,
	"minimum_age":                    true,
	"maximum_age":                    true,
	"healthy_volunteers":             true,
	"enrollment":                     true,
	"enrollment_type":                true,
	"primary_outcome_measure":        true,
	"primary_outcome_frame":          true,
	"primary_outcome_description":    true,
	"secondary_outcome_measure":      true,
	"secondary_outcome_time_frame":   true,
	"secondary_outcome_description":  true,
	"arm_group_arm_group_label":      true,
	"arm_group_arm_group_type":       true,
	"arm_group_description":          true,
	"location_name":                  true,
	"location_city":                  true,
	"location_country":               true,
	"patient_data_all":               true,
	"patient_data_sharing_ipd":       true,
	"sponsors_agency":                true,
	"sponsors_agency_class":          true,
	"publications_reference":         true,
	"publications_pmid":              true,
}
