package love

var fieldMap = []struct {
	Database string
	Name     string
}{
	{"plasma", "Plasma"},
	{"cove_screening", "Cove screening"},
	{"cove_import_date", "cove_import_date"},
	{"cove_update_date", "cove_update_date"},
	{"registry", "registry"},
	{"key", "Key"},
	{"item_type", "Item Type"},
	{"publication_year", "Publication Year"},
	{"author", "Author"},
	{"title", "Title"},
	{"publication_title", "Publication Title"},
	{"isbn", "ISBN"},
	{"issn", "ISSN"},
	{"doi", "DOI"},
	{"url", "Url"},
	{"abstract_note", "Abstract Note"},
	{"date", "Date"},
	{"date_added", "Date Added"},
	{"date_modified", "Date Modified"},
	{"access_date", "Access Date"},
	{"pages", "Pages"},
	{"num_pages", "Num Pages"},
	{"issue", "Issue"},
	{"volume", "Volume"},
	{"number_of_volumes", "Number Of Volumes"},
	{"journal_abbreviation", "Journal Abbreviation"},
	{"short_title", "Short Title"},
	{"series", "Series"},
	{"series_number", "Series Number"},
	{"series_text", "Series Text"},
	{"series_title", "Series Title"},
	{"publisher", "Publisher"},
	{"place", "Place"},
	{"language", "Language"},
	{"rights", "Rights"},
	{"type", "Type"},
	{"archive", "Archive"},
	{"archive_location", "Archive Location"},
	{"library_catalog", "Library Catalog"},
	{"call_number", "Call Number"},
	{"extra", "Extra"},
	{"notes", "Notes"},
	{"file_attachements", "File Attachments"},
	{"link_attachments", "Link Attachments"},
	{"manual_tags", "Manual Tags"},
	{"automatic_tags", "Automatic Tags"},
	{"editor", "Editor"},
	{"series_editor", "Series Editor"},
	{"translator", "Translator"},
	{"contributor", "Contributor"},
	{"attorney_agent", "Attorney Agent"},
	{"book_author", "Book Author"},
	{"cast_member", "Cast Member"},
	{"commenter", "Commenter"},
	{"composer", "Composer"},
	{"cosponsor", "Cosponsor"},
	{"counsel", "Counsel"},
	{"interviewer", "Interviewer"},
	{"producer", "Producer"},
	{"recipient", "Recipient"},
	{"reviewed_author", "Reviewed Author"},
	{"scriptwriter", "Scriptwriter"},
	{"words_by", "Words by"},
	{"guest", "Guest"},
	{"number", "Number"},
	{"edition", "Edition"},
	{"running_time", "Running Time"},
	{"scale", "Scale"},
	{"medium", "Medium"},
	{"artwork_size", "Artwork Size"},
	{"filing_date", "Filing Date"},
	{"application_number", "Application Number"},
	{"assignee", "Assignee"},
	{"issuing_authority", "Issuing Authority"},
	{"country", "Country"},
	{"meeting_name", "Meeting Name"},
	{"conference_name", "Conference Name"},
	{"court", "Court"},
	{"references", "References"},
	{"reporter", "Reporter"},
	{"legal_status", "Legal Status"},
	{"priority_numbers", "Priority Numbers"},
	{"programming_language", "Programming Language"},
	{"version", "Version"},
	{"system", "System"},
	{"code", "Code"},
	{"code_number", "Code Number"},
	{"section", "Section"},
	{"session", "Session"},
	{"committee", "Committee"},
	{"history", "History"},
	{"legislative_body", "Legislative Body"},
}
