package ictrp

var fieldMap = []struct {
	Database string
	Name     string
}{
	{"cove_screening", "cove_screening"},
	{"cove_import_date", "cove_import_date"},
	{"cove_update_date", "cove_update_date"},
	{"trial_id", "TrialID"},
	{"last_refreshed_on", "Last Refreshed on"},
	{"public_title", "Public title"},
	{"scientific_title", "Scientific title"},
	{"acronym", "Acronym"},
	{"primary_sponsor", "Primary sponsor"},
	{"date_registration", "Date registration"},
	{"date_registration_3", "Date registration3"},
	{"export_date", "Export date"},
	{"source_register", "Source Register"},
	{"web_address", "web address"},
	{"recruitment_status", "Recruitment Status"},
	{"other_records", "other records"},
	{"inclusion_agemin", "Inclusion agemin"},
	{"inclusion_agemax", "Inclusion agemax"},
	{"inclusion_gender", "Inclusion gender"},
	{"date_enrollement", "Date enrollement"},
	{"target_size", "Target size"},
	{"study_type", "Study type"},
	{"study_design", "Study design"},
	{"phase", "Phase"},
	{"countries", "Countries"},
	{"contact_firstname", "Contact Firstname"},
	{"contact_lastname", "Contact Lastname"},
	{"contact_address", "Contact Address"},
	{"contact_email", "Contact Email"},
	{"contact_tel", "Contact Tel"},
	{"contact_affiliation", "Contact Affiliation"},
	{"inclusion_criteria", "Inlcusion Criteria"},
	{"exclusion_criteria", "Exclusion Criteria"},
	{"condition", "Condition"},
	{"intervention", "Intervention"},
	{"primary_outcome", "Primary outcome"},
	{"results_date_posted", "results date posted"},
	{"results_date_completed", "results date completed"},
	{"results_url_link", "results url link"},
	{"retrospective_flag", "Retrospective flag"},
	{"bridging_flag_truefalse", "Bridging flag truefalse"},
	{"bridged_type", "Bridged type"},
	{"results_yes_no", "results yes no"},
}
