CREATE TABLE `cove_basic` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `owner` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_on` timestamp NULL DEFAULT NULL,
  `modified_by` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `modified_on` timestamp NULL DEFAULT NULL,
  `is_covid` varchar(12) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `is_trial` varchar(12) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `is_observational` varchar(12) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'no',
  `is_duplicate` varchar(12) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'no',
  `review_status` mediumtext COLLATE utf8mb4_unicode_ci,
  `reviewer_name` mediumtext COLLATE utf8mb4_unicode_ci,
  `source` mediumtext COLLATE utf8mb4_unicode_ci,
  `source_id` mediumtext COLLATE utf8mb4_unicode_ci,
  `entry_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `entry_type_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `title` mediumtext COLLATE utf8mb4_unicode_ci,
  `abstract` mediumtext COLLATE utf8mb4_unicode_ci,
  `authors` mediumtext COLLATE utf8mb4_unicode_ci,
  `corresp_author_lastname` mediumtext COLLATE utf8mb4_unicode_ci,
  `corresp_author_lastname_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `corresp_author_email` mediumtext COLLATE utf8mb4_unicode_ci,
  `corresp_author_email_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `authors_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `abstract_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `title_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `journal` mediumtext COLLATE utf8mb4_unicode_ci,
  `journal_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `doi` mediumtext COLLATE utf8mb4_unicode_ci,
  `doi_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `status_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `status` mediumtext COLLATE utf8mb4_unicode_ci,
  `country` mediumtext COLLATE utf8mb4_unicode_ci,
  `country_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `covid_status` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `covid_status_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `randomized` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `randomized_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `blinding` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `blinding_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `longitudinal_structure` mediumtext COLLATE utf8mb4_unicode_ci,
  `longitudinal_structure_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `n_arms_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `n_enrollment_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `population_condition` mediumtext COLLATE utf8mb4_unicode_ci,
  `population_condition_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `url` mediumtext COLLATE utf8mb4_unicode_ci,
  `url_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `status_date_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `population_gender` mediumtext COLLATE utf8mb4_unicode_ci,
  `population_gender_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `population_age` mediumtext COLLATE utf8mb4_unicode_ci,
  `population_age_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `intervention_type` json DEFAULT NULL,
  `intervention_type_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `intervention_name` mediumtext COLLATE utf8mb4_unicode_ci,
  `intervention_name_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `control` mediumtext COLLATE utf8mb4_unicode_ci,
  `control_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `out_primary_measure` mediumtext COLLATE utf8mb4_unicode_ci,
  `out_primary_desc` mediumtext COLLATE utf8mb4_unicode_ci,
  `out_primary_timeframe` mediumtext COLLATE utf8mb4_unicode_ci,
  `out_primary_measure_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `out_primary_desc_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `out_primary_timeframe_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `start_date` mediumtext COLLATE utf8mb4_unicode_ci,
  `start_date_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `end_date` mediumtext COLLATE utf8mb4_unicode_ci,
  `end_date_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `results_available` json DEFAULT NULL,
  `results_available_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `results_expected_date` mediumtext COLLATE utf8mb4_unicode_ci,
  `results_expected_date_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `ipd_sharing` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ipd_sharing_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `linkage_info` mediumtext COLLATE utf8mb4_unicode_ci,
  `linkage_info_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `out_secondary_desc` mediumtext COLLATE utf8mb4_unicode_ci,
  `out_secondary_timeframe` mediumtext COLLATE utf8mb4_unicode_ci,
  `out_secondary_measure_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `out_secondary_desc_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `out_secondary_timeframe_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `inclusion_criteria` text COLLATE utf8mb4_unicode_ci,
  `inclusion_criteria_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `exclusion_criteria` mediumtext COLLATE utf8mb4_unicode_ci,
  `exclusion_criteria_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `funding` mediumtext COLLATE utf8mb4_unicode_ci,
  `funding_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `funding_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `funding_type_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `protocol_available` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `protocol_available_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `protocol_link` mediumtext COLLATE utf8mb4_unicode_ci,
  `protocol_link_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `extraction_comment` mediumtext COLLATE utf8mb4_unicode_ci,
  `out_secondary_measure` mediumtext COLLATE utf8mb4_unicode_ci,
  `registration_date` mediumtext COLLATE utf8mb4_unicode_ci,
  `registration_date_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `population_type` mediumtext COLLATE utf8mb4_unicode_ci,
  `population_type_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `purpose_trial` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `purpose_trial_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `intervention_substance` mediumtext COLLATE utf8mb4_unicode_ci,
  `intervention_substance_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `control_type` json DEFAULT NULL,
  `control_type_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `status_date_migration` date DEFAULT NULL,
  `status_date_old` mediumtext COLLATE utf8mb4_unicode_ci,
  `status_date` date DEFAULT NULL,
  `publication` mediumtext COLLATE utf8mb4_unicode_ci,
  `publication_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `publication_trial_registration` mediumtext COLLATE utf8mb4_unicode_ci,
  `publication_trial_registration_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `n_enrollment` bigint(11) DEFAULT NULL,
  `countries` mediumtext COLLATE utf8mb4_unicode_ci,
  `countries_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `continents` mediumtext COLLATE utf8mb4_unicode_ci,
  `continents_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `international` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `international_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  `n_arms` int(11) DEFAULT NULL,
  `is_rct` varchar(12) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `project_identifiers` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `results_url` mediumtext COLLATE utf8mb4_unicode_ci,
  `results_url_certainty` mediumtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;