CREATE TABLE `screening_ictrp` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `owner` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_on` timestamp NULL DEFAULT NULL,
  `modified_by` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `modified_on` timestamp NULL DEFAULT NULL,
  `cove_screening` mediumtext COLLATE utf8mb4_unicode_ci,
  `in_source` tinyint(1) DEFAULT NULL,
  `cove_import_date` date DEFAULT NULL,
  `cove_update_date` date DEFAULT NULL,
  `trial_id` mediumtext COLLATE utf8mb4_unicode_ci,
  `public_title` mediumtext COLLATE utf8mb4_unicode_ci,
  `scientific_title` mediumtext COLLATE utf8mb4_unicode_ci,
  `acronym` mediumtext COLLATE utf8mb4_unicode_ci,
  `primary_sponsor` mediumtext COLLATE utf8mb4_unicode_ci,
  `date_registration` mediumtext COLLATE utf8mb4_unicode_ci,
  `date_registration_3` mediumtext COLLATE utf8mb4_unicode_ci,
  `export_date` mediumtext COLLATE utf8mb4_unicode_ci,
  `source_register` mediumtext COLLATE utf8mb4_unicode_ci,
  `web_address` mediumtext COLLATE utf8mb4_unicode_ci,
  `recruitment_status` mediumtext COLLATE utf8mb4_unicode_ci,
  `other_records` mediumtext COLLATE utf8mb4_unicode_ci,
  `inclusion_agemin` mediumtext COLLATE utf8mb4_unicode_ci,
  `inclusion_agemax` mediumtext COLLATE utf8mb4_unicode_ci,
  `inclusion_gender` mediumtext COLLATE utf8mb4_unicode_ci,
  `date_enrollement` mediumtext COLLATE utf8mb4_unicode_ci,
  `target_size` mediumtext COLLATE utf8mb4_unicode_ci,
  `study_type` mediumtext COLLATE utf8mb4_unicode_ci,
  `study_design` mediumtext COLLATE utf8mb4_unicode_ci,
  `phase` mediumtext COLLATE utf8mb4_unicode_ci,
  `countries` mediumtext COLLATE utf8mb4_unicode_ci,
  `contact_firstname` mediumtext COLLATE utf8mb4_unicode_ci,
  `contact_lastname` mediumtext COLLATE utf8mb4_unicode_ci,
  `contact_address` mediumtext COLLATE utf8mb4_unicode_ci,
  `contact_email` mediumtext COLLATE utf8mb4_unicode_ci,
  `contact_tel` mediumtext COLLATE utf8mb4_unicode_ci,
  `contact_affiliation` mediumtext COLLATE utf8mb4_unicode_ci,
  `inclusion_criteria` mediumtext COLLATE utf8mb4_unicode_ci,
  `exclusion_criteria` mediumtext COLLATE utf8mb4_unicode_ci,
  `condition` mediumtext COLLATE utf8mb4_unicode_ci,
  `intervention` mediumtext COLLATE utf8mb4_unicode_ci,
  `primary_outcome` mediumtext COLLATE utf8mb4_unicode_ci,
  `results_date_posted` mediumtext COLLATE utf8mb4_unicode_ci,
  `results_date_completed` mediumtext COLLATE utf8mb4_unicode_ci,
  `results_url_link` mediumtext COLLATE utf8mb4_unicode_ci,
  `retrospective_flag` mediumtext COLLATE utf8mb4_unicode_ci,
  `bridging_flag_truefalse` mediumtext COLLATE utf8mb4_unicode_ci,
  `bridged_type` mediumtext COLLATE utf8mb4_unicode_ci,
  `results_yes_no` mediumtext COLLATE utf8mb4_unicode_ci,
  `last_refreshed_on` mediumtext COLLATE utf8mb4_unicode_ci,
  `redundants` tinyint(1) DEFAULT NULL,
  `source_duplicates` tinyint(1) DEFAULT NULL,
  `cove_screening_comment` mediumtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;