CREATE TABLE `screening_clinicaltrials` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `owner` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_on` timestamp NULL DEFAULT NULL,
  `modified_by` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `modified_on` timestamp NULL DEFAULT NULL,
  `cove_screening` mediumtext COLLATE utf8mb4_unicode_ci,
  `in_source` tinyint(1) DEFAULT NULL,
  `cove_import_date` date DEFAULT NULL,
  `cove_update_date` date DEFAULT NULL,
  `nct_id` mediumtext COLLATE utf8mb4_unicode_ci,
  `date_study_first_submitted` mediumtext COLLATE utf8mb4_unicode_ci,
  `date_study_first_posted` mediumtext COLLATE utf8mb4_unicode_ci,
  `date_last_update_posted` mediumtext COLLATE utf8mb4_unicode_ci,
  `date_started` mediumtext COLLATE utf8mb4_unicode_ci,
  `date_started_type` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `date_completed` mediumtext COLLATE utf8mb4_unicode_ci,
  `date_completed_type` mediumtext COLLATE utf8mb4_unicode_ci,
  `status` mediumtext COLLATE utf8mb4_unicode_ci,
  `brief_title` mediumtext COLLATE utf8mb4_unicode_ci,
  `detailed_description` mediumtext COLLATE utf8mb4_unicode_ci,
  `study_type` mediumtext COLLATE utf8mb4_unicode_ci,
  `phase` mediumtext COLLATE utf8mb4_unicode_ci,
  `allocation` mediumtext COLLATE utf8mb4_unicode_ci,
  `intervention_model` mediumtext COLLATE utf8mb4_unicode_ci,
  `intervention_model_description` mediumtext COLLATE utf8mb4_unicode_ci,
  `primary_purpose` mediumtext COLLATE utf8mb4_unicode_ci,
  `masking` mediumtext COLLATE utf8mb4_unicode_ci,
  `condition` mediumtext COLLATE utf8mb4_unicode_ci,
  `intervention_type` mediumtext COLLATE utf8mb4_unicode_ci,
  `intervention_name` mediumtext COLLATE utf8mb4_unicode_ci,
  `intervention_desc` mediumtext COLLATE utf8mb4_unicode_ci,
  `eligibility_criteria` mediumtext COLLATE utf8mb4_unicode_ci,
  `gender` mediumtext COLLATE utf8mb4_unicode_ci,
  `minimum_age` mediumtext COLLATE utf8mb4_unicode_ci,
  `maximum_age` mediumtext COLLATE utf8mb4_unicode_ci,
  `healthy_volunteers` mediumtext COLLATE utf8mb4_unicode_ci,
  `enrollment` mediumtext COLLATE utf8mb4_unicode_ci,
  `enrollment_type` mediumtext COLLATE utf8mb4_unicode_ci,
  `primary_outcome_measure` mediumtext COLLATE utf8mb4_unicode_ci,
  `primary_outcome_frame` mediumtext COLLATE utf8mb4_unicode_ci,
  `primary_outcome_description` mediumtext COLLATE utf8mb4_unicode_ci,
  `secondary_outcome_measure` mediumtext COLLATE utf8mb4_unicode_ci,
  `secondary_outcome_time_frame` mediumtext COLLATE utf8mb4_unicode_ci,
  `secondary_outcome_description` mediumtext COLLATE utf8mb4_unicode_ci,
  `arm_group_arm_group_label` mediumtext COLLATE utf8mb4_unicode_ci,
  `arm_group_arm_group_type` mediumtext COLLATE utf8mb4_unicode_ci,
  `arm_group_description` mediumtext COLLATE utf8mb4_unicode_ci,
  `location_name` mediumtext COLLATE utf8mb4_unicode_ci,
  `location_city` mediumtext COLLATE utf8mb4_unicode_ci,
  `location_country` mediumtext COLLATE utf8mb4_unicode_ci,
  `patient_data_all` mediumtext COLLATE utf8mb4_unicode_ci,
  `patient_data_sharing_ipd` mediumtext COLLATE utf8mb4_unicode_ci,
  `sponsors_agency` mediumtext COLLATE utf8mb4_unicode_ci,
  `sponsors_agency_class` mediumtext COLLATE utf8mb4_unicode_ci,
  `publications_reference` mediumtext COLLATE utf8mb4_unicode_ci,
  `publications_pmid` mediumtext COLLATE utf8mb4_unicode_ci,
  `official_title` mediumtext COLLATE utf8mb4_unicode_ci,
  `brief_summary` mediumtext COLLATE utf8mb4_unicode_ci,
  `redundants` tinyint(1) DEFAULT NULL,
  `source_duplicates` tinyint(1) DEFAULT NULL,
  `date_results_first_posted` mediumtext COLLATE utf8mb4_unicode_ci,
  `cove_screening_comment` mediumtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;