package sources

var countryMap = []struct {
	Term      string
	Mapping   string
	Country   bool
	Continent string
}{
	{"Mexico", "Mexico", true, "North America"},
	{"Italy", "Italy", true, "Europe"},
	{"United States", "USA", true, "North America"},
	{"Brazil", "Brazil", true, "South America"},
	{"Europe", "Europe", false, "Europe"},
	{"European", "Europe", false, "Europe"},
	{"Asia", "Asia", false, "Asia"},
	{"ASIA", "Asia", false, "Asia"},
	{"International", "International", false, ""},
	{"China", "China", true, "Asia"},
	{"P.R.China", "China", true, "Asia"},
	{"China?", "China", true, "Asia"},
	{"china", "China", true, "Asia"},
	{"Chinese", "China", true, "Asia"},
	{"Spain", "Spain", true, "Europe"},
	{"Canada", "Canada", true, "North America"},
	{"France", "France", true, "Europe"},
	{"Belgium", "Belgium", true, "Europe"},
	{"Luxembourg", "Luxembourg", true, "Europe"},
	{"Luxemburg", "Luxembourg", true, "Europe"},
	{"Netherlands", "Netherlands", true, "Europe"},
	{"Holland", "Netherlands", true, "Europe"},
	{"Germany", "Germany", true, "Europe"},
	{"Uzbekistan", "Uzbekistan", true, "Europe"},
	{"United Kingdom", "United Kingdom", true, "Europe"},
	{"Northern Ireland", "United Kingdom", true, "Europe"},
	{"England", "United Kingdom", true, "Europe"},
	{"Wales", "United Kingdom", true, "Europe"},
	{"Scotland", "United Kingdom", true, "Europe"},
	{"UK", "United Kingdom", true, "Europe"},
	{"United Kindgdom", "United Kingdom", true, "Europe"},
	{"Equatorial Guinea", "Equatorial Guinea", true, "Africa"},
	{"Swaziland", "Swaziland", true, "Africa"},
	{"Burkina Faso", "Burkina Faso", true, "Africa"},
	{"Cameroon", "Cameroon", true, "Africa"},
	{"Sierra Leone", "Sierra Leone", true, "Africa"},
	{"Mali", "Mali", true, "Africa"},
	{"Tanzania", "Tanzania", true, "Africa"},
	{"Mozambique", "Mozambique", true, "Africa"},
	{"Gambia", "Gambia", true, "Africa"},
	{"Iran", "Iran", true, "Asia"},
	{"Americas", "North America", false, "North America"},
	{"Bahamas", "Bahamas", true, "North America"},
	{"Belize", "Belize", true, "North America"},
	{"Americas", "South America", false, "South America"},
	{"Columbia", "Columbia", true, "South America"},
	{"Poland", "Poland", true, "Europe"},
	{"Poland Rep", "Poland", true, "Europe"},
	{"Korea, South", "South Korea", true, "Asia"},
	{"Trinidad and Tobago", "Trinidad and Tobago", true, "South America"},
	{"Monaco", "Monaco", true, "Europe"},
	{"Modalvia", "Moldova", true, "Europe"},
	{"Albania", "Albania", true, "Europe"},
	{"Macedonia", "Macedonia", true, "Europe"},
	{"Morocco", "Morocco", true, "Africa"},
	{"Korea, Republic of", "South Korea", true, "Asia"},
	{"Korea South", "South Korea", true, "Asia"},
	{"Oceania", "Oceania", false, "Australia/Oceania"},
	{"Gibraltar", "Gibraltar", true, "Europe"},
	{"Africa", "Africa", false, "Africa"},
	{"AFRICA", "Africa", false, "Africa"},
	{"South America", "South America", false, "South America"},
	{"South America", "South America", false, "South America"},
	{"Togo", "Togo", true, "Africa"},
	{"Madagascar", "Madagascar", true, "Africa"},
	{"Argentina", "Argentina", true, "South America"},
	{"Suriname", "Suriname", true, "South America"},
	{"Paraguay", "Paraguay", true, "South America"},
	{"Egypt", "Egypt", true, "Africa"},
	{"Korea", "South Korea", true, "Asia"},
	{"Cambodia", "Cambodia", true, "Asia"},
	{"Hungary", "Hungary", true, "Europe"},
	{"USA", "USA", true, "North America"},
	{"Pakistan", "Pakistan", true, "Asia"},
	{"Tunisia", "Tunesia", true, "Africa"},
	{"Turkey", "Turkey", true, "Asia"},
	{"Turkey", "Turkey", true, "Europe"},
	{"na", "", false, ""},
	{"Denmark", "Denmark", true, "Europe"},
	{"Colombia", "Colombia", true, "South America"},
	{"India", "India", true, "Asia"},
	{"Australia", "Australia", true, "Australia/Oceania"},
	{"The Netherlands", "Netherlands", true, "Europe"},
	{"Nederland", "Netherlands", true, "Europe"},
	{"Switzerland", "Switzerland", true, "Europe"},
	{"Haiti", "Haiti", true, "South America"},
	{"Botswana", "Botswana", true, "Africa"},
	{"Réunion", "Réunion", true, "Africa"},
	{"Martinique", "Martinique", true, "North America"},
	{"Bolivia", "Bolivia", true, "South America"},
	{"Guyana", "Guyana", true, "South America"},
	{"Cyprus", "Cyprus", true, "Europe"},
	{"Greece", "Greece", true, "Europe"},
	{"Chile", "Chile", true, "South America"},
	{"Jordan", "Jordan", true, "Asia"},
	{"Iran, Islamic Republic of", "Iran", true, "Asia"},
	{"Republic of the Philippines", "Philippines", true, "Asia"},
	{"Iceland", "Iceland", true, "Europe"},
	{"Bahrain", "Bahrain", true, "Asia"},
	{"Bosnia and Herzegovina", "Bosnia and Herzegovina", true, "Europe"},
	{"South Africa", "South Africa", true, "Africa"},
	{"Dominican Republic", "Dominican Republic", true, "South America"},
	{"Dominica", "Dominica", true, "South America"},
	{"Israel", "Israel", true, "Europe"},
	{"Slovenia", "Slovenia", true, "Europe"},
	{"Austria", "Austria", true, "Europe"},
	{"Hong Kong", "Hong Kong", true, "Asia"},
	{"Sweden", "Sweden", true, "Europe"},
	{"Saudi Arabia", "Saudi Arabia", true, "Asia"},
	{"Russian Federation", "Russia", true, "Europe"},
	{"Russian Federation", "Russia", true, "Asia"},
	{"Russia", "Russia", true, "Asia"},
	{"Russia", "Russia", true, "Europe"},
	{"Sudan", "Sudan", true, "Africa"},
	{"Taiwan", "Taiwan", true, "Asia"},
	{"Senegal", "Senegal", true, "Africa"},
	{"Benin", "Benin", true, "Africa"},
	{"Peru", "Peru", true, "South America"},
	{"Peru Rep", "Peru", true, "South America"},
	{"Qatar", "Qatar", true, "Asia"},
	{"Bangladesh", "Bangladesh", true, "Asia"},
	{"Singapore", "Singapore", true, "Asia"},
	{"Malaysia", "Malaysia", true, "Asia"},
	{"MALAYSIA", "Malaysia", true, "Asia"},
	{"Mongolia", "Mongolia", true, "Asia"},
	{"New Caledonia", "New Caledonia", true, "Australia/Oceania"},
	{"New Caledonia", "New Caledonia", true, "Europe"},
	{"Guadeloupe", "Guadeloupe", true, "South America"},
	{"Guadeloupe", "Guadeloupe", true, "Europe"},
	{"Indonesia", "Indonesia", true, "Asia"},
	{"Ecuador", "Ecuador", true, "South America"},
	{"Norway", "Norway", true, "Europe"},
	{"Honduras", "Honduras", true, "South America"},
	{"Japan", "Japan", true, "Asia"},
	{"Portugal", "Portugal", true, "Europe"},
	{"Ethiopia", "Ethiopia", true, "Africa"},
	{"Zambia", "Zambia", true, "Africa"},
	{"Iran (Islamic Republic of)", "Iran", true, "Asia"},
	{"Ghana", "Ghana", true, "Africa"},
	{"Nigeria", "Nigeria", true, "Africa"},
	{"Ireland", "Ireland", true, "Europe"},
	{"Thailand", "Thailand", true, "Asia"},
	{"Serbia", "Serbia", true, "Europe"},
	{"Finland", "Finland", true, "Europe"},
	{"Lebanon", "Lebanon", true, "Asia"},
	{"KOREA", "South Korea", true, "Asia"},
	{"Sri Lanka", "Sri Lanka", true, "Asia"},
	{"Ukraine", "Ukraine", true, "Europe"},
	{"Romania", "Romania", true, "Europe"},
	{"Moldova, Republic of", "Moldova", true, "Europe"},
	{"Lithuania", "Lithuania", true, "Europe"},
	{"Latvia", "Latvia", true, "Europe"},
	{"Oman", "Oman", true, "Asia"},
	{"United Arab Emirates", "United Arab Emirates", true, "Asia"},
	{"Cuba", "Cuba", true, "South America"},
	{"Mexico", "Mexico", true, "North America"},
	{"Slovakia", "Slovakia", true, "Europe"},
	{"Bulgaria", "Bulgaria", true, "Europe"},
	{"Guinea-Bissau", "Guinea-Bissau", true, "Africa"},
	{"Côte D'Ivoire", "Côte D'Ivoire", true, "Africa"},
	{"Iraq", "Iraq", true, "Asia"},
	{"Rwanda", "Rwanda", true, "Asia"},
	{"Kazakhstan", "Kazakhstan", true, "Asia"},
	{"Azerbaijan", "Azerbaijan", true, "Asia"},
	{"Barbados", "Barbados", true, "South America"},
	{"Czech Republic", "Czechia", true, "Europe"},
	{"Czech Rep", "Czechia", true, "Europe"},
	{"Czechia", "Czechia", true, "Europe"},
	{"Croatia", "Croatia", true, "Europe"},
	{"Estonia", "Estonia", true, "Europe"},
	{"Guatemala", "Guatemala", true, "South America"},
	{"Jamaica", "Jamaica", true, "South America"},
	{"Zimbabwe", "Zimbabwe", true, "Africa"},
	{"Cape Verde", "Cape Verde", true, "Africa"},
	{"Kenya", "Kenya", true, "Africa"},
	{"Lao People's Democratic Republic", "Laos", true, "Asia"},
	{"Uganda", "Uganda", true, "Africa"},
	{"Malawi", "Malawi", true, "Africa"},
	{"Vietnam", "Vietnam", true, "Asia"},
	{"Macedonia, the former Yugoslav Republic of", "Macedonia", true, "Europe"},
	{"EUROPE", "Europe", false, "Europe"},
	{"European", "Europe", false, "Europe"},
	{"ASIA", "Asia", false, "Asia"},
	{"Asia(except Japan)", "Asia", false, "Asia"},
	{"Philippines", "Philippines", true, "Asia"},
	{"Guinea", "Guinea", true, "Africa"},
	{"Niger", "Niger", true, "Africa"},
	{"Panama", "Panama", true, "South America"},
	{"French Guiana", "French Guiana", true, "South America"},
	{"United States of America", "USA", true, "North America"},
	{"Puerto Rico", "Puerto Rico", true, "South America"},
	{"New Zealand", "New Zealand", true, "Australia/Oceania"},
	{"North Macedonia", "North Macedonia", true, "Europe"},
	{"Kuwait", "Kuwait", true, "Asia"},
	{"Congo, The Democratic Republic of the", "Congo", true, "Africa"},
	{"Democratic Republic of the Congo", "Congo", true, "Africa"},
	{"SOUTH AMERICA", "South America", false, "South America"},
	{"Georgia", "Georgia", true, "Asia"},
	{"Laos", "Laos", true, "Asia"},
	{"Belarus", "Belarus", true, "Europe"},
	{"Kyrgyzstan", "Kyrgyzstan", true, "Asia"},
	{"Nepal", "Nepal", true, "Asia"},
	{"North America", "North America", false, "North America"},
	{"Japan,Asia(except Japan),Australia,Europe", "International", false, "International"},
	{"Costa Rica", "Costa Rica", true, "South America"},
	{"AFRICA", "Africa", false, "Africa"},
	{"Africa", "Africa", false, "Africa"},
}
